--Insert into Area
INSERT INTO Area (AreaID, AreaName, Description, SecurityLevelRequired) VALUES
(1, 'Warehouse A', 'Warehouse A - designated for specific operations.', 2),
(2, 'Warehouse B', 'Warehouse B - designated for specific operations.', 3),
(3, 'Main Office', 'Main Office - designated for specific operations.', 4),
(4, 'Security Room', 'Security Room - designated for specific operations.', 5),
(5, 'Parking Lot A', 'Parking Lot A - designated for specific operations.', 1),
(6, 'Parking Lot B', 'Parking Lot B - designated for specific operations.', 2),
(7, 'Cafeteria', 'Cafeteria - designated for specific operations.', 3),
(8, 'Laboratory 1', 'Laboratory 1 - designated for specific operations.', 4),
(9, 'Laboratory 2', 'Laboratory 2 - designated for specific operations.', 5),
(10, 'Server Room', 'Server Room - designated for specific operations.', 1),
(11, 'Conference Hall', 'Conference Hall - designated for specific operations.', 2),
(12, 'HR Office', 'HR Office - designated for specific operations.', 3),
(13, 'Reception', 'Reception - designated for specific operations.', 4),
(14, 'Control Center', 'Control Center - designated for specific operations.', 5),
(15, 'Generator Room', 'Generator Room - designated for specific operations.', 1),
(16, 'Data Center', 'Data Center - designated for specific operations.', 2),
(17, 'R&D Unit', 'R&D Unit - designated for specific operations.', 3),
(18, 'Assembly Line A', 'Assembly Line A - designated for specific operations.', 4),
(19, 'Assembly Line B', 'Assembly Line B - designated for specific operations.', 5),
(20, 'Medical Room', 'Medical Room - designated for specific operations.', 1),
(21, 'Break Room', 'Break Room - designated for specific operations.', 2),
(22, 'Loading Dock', 'Loading Dock - designated for specific operations.', 3),
(23, 'Testing Facility', 'Testing Facility - designated for specific operations.', 4),
(24, 'Customer Service', 'Customer Service - designated for specific operations.', 5),
(25, 'Executive Office', 'Executive Office - designated for specific operations.', 1),
(26, 'Training Room', 'Training Room - designated for specific operations.', 2),
(27, 'Lobby', 'Lobby - designated for specific operations.', 3),
(28, 'Locker Room', 'Locker Room - designated for specific operations.', 4),
(29, 'Emergency Exit A', 'Emergency Exit A - designated for specific operations.', 5),
(30, 'Emergency Exit B', 'Emergency Exit B - designated for specific operations.', 1),
(31, 'Storage Room 1', 'Storage Room 1 - designated for specific operations.', 2),
(32, 'Storage Room 2', 'Storage Room 2 - designated for specific operations.', 3),
(33, 'Storage Room 3', 'Storage Room 3 - designated for specific operations.', 4),
(34, 'Security Checkpoint', 'Security Checkpoint - designated for specific operations.', 5),
(35, 'Visitor Lounge', 'Visitor Lounge - designated for specific operations.', 1),
(36, 'Observation Deck', 'Observation Deck - designated for specific operations.', 2),
(37, 'Mechanical Room', 'Mechanical Room - designated for specific operations.', 3),
(38, 'Technical Support', 'Technical Support - designated for specific operations.', 4),
(39, 'Assembly Line C', 'Assembly Line C - designated for specific operations.', 5),
(40, 'Shipping Office', 'Shipping Office - designated for specific operations.', 1),
(41, 'Inspection Room', 'Inspection Room - designated for specific operations.', 2),
(42, 'Library', 'Library - designated for specific operations.', 3),
(43, 'Fire Exit A', 'Fire Exit A - designated for specific operations.', 4),
(44, 'Fire Exit B', 'Fire Exit B - designated for specific operations.', 5),
(45, 'Employee Lounge', 'Employee Lounge - designated for specific operations.', 1),
(46, 'Production Floor', 'Production Floor - designated for specific operations.', 2),
(47, 'Maintenance Room', 'Maintenance Room - designated for specific operations.', 3),
(48, 'VIP Lounge', 'VIP Lounge - designated for specific operations.', 4),
(49, 'Research Wing', 'Research Wing - designated for specific operations.', 5),
(50, 'Data Processing Unit', 'Data Processing Unit - designated for specific operations.', 1),
(51, 'Operations Control', 'Operations Control - designated for specific operations.', 2),
(52, 'Management Office', 'Management Office - designated for specific operations.', 3),
(53, 'Surveillance Room', 'Surveillance Room - designated for specific operations.', 4),
(54, 'Underground Bunker', 'Underground Bunker - designated for specific operations.', 5),
(55, 'Solar Panel Area', 'Solar Panel Area - designated for specific operations.', 1),
(56, 'Cooling Plant', 'Cooling Plant - designated for specific operations.', 2),
(57, 'Fuel Storage', 'Fuel Storage - designated for specific operations.', 3),
(58, 'Medical Lab', 'Medical Lab - designated for specific operations.', 4),
(59, 'Fire Safety Room', 'Fire Safety Room - designated for specific operations.', 5),
(60, 'Server Backup Room', 'Server Backup Room - designated for specific operations.', 1),
(61, 'Central Command', 'Central Command - designated for specific operations.', 2),
(62, 'Satellite Control', 'Satellite Control - designated for specific operations.', 3),
(63, 'AI Development Lab', 'AI Development Lab - designated for specific operations.', 4),
(64, 'Cybersecurity Wing', 'Cybersecurity Wing - designated for specific operations.', 5),
(65, 'Legal Office', 'Legal Office - designated for specific operations.', 1),
(66, 'Archive Room', 'Archive Room - designated for specific operations.', 2),
(67, 'Emergency Response Unit', 'Emergency Response Unit - designated for specific operations.', 3),
(68, 'Drones Testing Zone', 'Drones Testing Zone - designated for specific operations.', 4),
(69, 'Public Relations Office', 'Public Relations Office - designated for specific operations.', 5),
(70, 'Press Conference Room', 'Press Conference Room - designated for specific operations.', 1),
(71, 'Simulation Lab', 'Simulation Lab - designated for specific operations.', 2),
(72, 'Robotics Division', 'Robotics Division - designated for specific operations.', 3),
(73, 'Weapons Testing Facility', 'Weapons Testing Facility - designated for specific operations.', 4),
(74, 'Hazardous Materials Storage', 'Hazardous Materials Storage - designated for specific operations.', 5),
(75, 'Quarantine Zone', 'Quarantine Zone - designated for specific operations.', 1),
(76, 'Biochemical Research Lab', 'Biochemical Research Lab - designated for specific operations.', 2),
(77, 'Nuclear Reactor Room', 'Nuclear Reactor Room - designated for specific operations.', 3),
(78, 'Meteorology Center', 'Meteorology Center - designated for specific operations.', 4),
(79, 'Greenhouse', 'Greenhouse - designated for specific operations.', 5),
(80, 'Animal Testing Lab', 'Animal Testing Lab - designated for specific operations.', 1),
(81, 'Submarine Dock', 'Submarine Dock - designated for specific operations.', 2),
(82, 'Air Traffic Control Tower', 'Air Traffic Control Tower - designated for specific operations.', 3),
(83, 'Aircraft Hangar', 'Aircraft Hangar - designated for specific operations.', 4),
(84, 'Spacecraft Assembly', 'Spacecraft Assembly - designated for specific operations.', 5),
(85, 'Rocket Testing Facility', 'Rocket Testing Facility - designated for specific operations.', 1),
(86, 'Astronaut Training Center', 'Astronaut Training Center - designated for specific operations.', 2),
(87, 'Underwater Research Lab', 'Underwater Research Lab - designated for specific operations.', 3),
(88, 'Seismology Center', 'Seismology Center - designated for specific operations.', 4),
(89, 'Deep Sea Exploration Unit', 'Deep Sea Exploration Unit - designated for specific operations.', 5),
(90, 'Mineral Extraction Plant', 'Mineral Extraction Plant - designated for specific operations.', 1),
(91, 'Ecological Research Zone', 'Ecological Research Zone - designated for specific operations.', 2),
(92, 'Climate Monitoring Station', 'Climate Monitoring Station - designated for specific operations.', 3),
(93, 'Antarctic Research Base', 'Antarctic Research Base - designated for specific operations.', 4),
(94, 'Desert Testing Grounds', 'Desert Testing Grounds - designated for specific operations.', 5),
(95, 'Restricted Area', 'Restricted Area - designated for specific operations.', 1),
(96, 'Warehouse A', 'Warehouse A - designated for specific operations.', 2),
(97, 'Warehouse B', 'Warehouse B - designated for specific operations.', 3),
(98, 'Main Office', 'Main Office - designated for specific operations.', 4),
(99, 'Security Room', 'Security Room - designated for specific operations.', 5),
(100, 'Parking Lot A', 'Parking Lot A - designated for specific operations.', 1),
(101, 'Parking Lot B', 'Parking Lot B - designated for specific operations.', 2),
(102, 'Cafeteria', 'Cafeteria - designated for specific operations.', 3),
(103, 'Laboratory 1', 'Laboratory 1 - designated for specific operations.', 4),
(104, 'Laboratory 2', 'Laboratory 2 - designated for specific operations.', 5),
(105, 'Server Room', 'Server Room - designated for specific operations.', 1),
(106, 'Conference Hall', 'Conference Hall - designated for specific operations.', 2),
(107, 'HR Office', 'HR Office - designated for specific operations.', 3),
(108, 'Reception', 'Reception - designated for specific operations.', 4),
(109, 'Control Center', 'Control Center - designated for specific operations.', 5),
(110, 'Generator Room', 'Generator Room - designated for specific operations.', 1),
(111, 'Data Center', 'Data Center - designated for specific operations.', 2),
(112, 'R&D Unit', 'R&D Unit - designated for specific operations.', 3),
(113, 'Assembly Line A', 'Assembly Line A - designated for specific operations.', 4),
(114, 'Assembly Line B', 'Assembly Line B - designated for specific operations.', 5),
(115, 'Medical Room', 'Medical Room - designated for specific operations.', 1),
(116, 'Break Room', 'Break Room - designated for specific operations.', 2),
(117, 'Loading Dock', 'Loading Dock - designated for specific operations.', 3),
(118, 'Testing Facility', 'Testing Facility - designated for specific operations.', 4),
(119, 'Customer Service', 'Customer Service - designated for specific operations.', 5),
(120, 'Executive Office', 'Executive Office - designated for specific operations.', 1),
(121, 'Training Room', 'Training Room - designated for specific operations.', 2),
(122, 'Lobby', 'Lobby - designated for specific operations.', 3),
(123, 'Locker Room', 'Locker Room - designated for specific operations.', 4),
(124, 'Emergency Exit A', 'Emergency Exit A - designated for specific operations.', 5),
(125, 'Emergency Exit B', 'Emergency Exit B - designated for specific operations.', 1),
(126, 'Storage Room 1', 'Storage Room 1 - designated for specific operations.', 2),
(127, 'Storage Room 2', 'Storage Room 2 - designated for specific operations.', 3),
(128, 'Storage Room 3', 'Storage Room 3 - designated for specific operations.', 4),
(129, 'Security Checkpoint', 'Security Checkpoint - designated for specific operations.', 5),
(130, 'Visitor Lounge', 'Visitor Lounge - designated for specific operations.', 1),
(131, 'Observation Deck', 'Observation Deck - designated for specific operations.', 2),
(132, 'Mechanical Room', 'Mechanical Room - designated for specific operations.', 3),
(133, 'Technical Support', 'Technical Support - designated for specific operations.', 4),
(134, 'Assembly Line C', 'Assembly Line C - designated for specific operations.', 5),
(135, 'Shipping Office', 'Shipping Office - designated for specific operations.', 1),
(136, 'Inspection Room', 'Inspection Room - designated for specific operations.', 2),
(137, 'Library', 'Library - designated for specific operations.', 3),
(138, 'Fire Exit A', 'Fire Exit A - designated for specific operations.', 4),
(139, 'Fire Exit B', 'Fire Exit B - designated for specific operations.', 5),
(140, 'Employee Lounge', 'Employee Lounge - designated for specific operations.', 1),
(141, 'Production Floor', 'Production Floor - designated for specific operations.', 2),
(142, 'Maintenance Room', 'Maintenance Room - designated for specific operations.', 3),
(143, 'VIP Lounge', 'VIP Lounge - designated for specific operations.', 4),
(144, 'Research Wing', 'Research Wing - designated for specific operations.', 5),
(145, 'Data Processing Unit', 'Data Processing Unit - designated for specific operations.', 1),
(146, 'Operations Control', 'Operations Control - designated for specific operations.', 2),
(147, 'Management Office', 'Management Office - designated for specific operations.', 3),
(148, 'Surveillance Room', 'Surveillance Room - designated for specific operations.', 4),
(149, 'Underground Bunker', 'Underground Bunker - designated for specific operations.', 5),
(150, 'Solar Panel Area', 'Solar Panel Area - designated for specific operations.', 1),
(151, 'Cooling Plant', 'Cooling Plant - designated for specific operations.', 2),
(152, 'Fuel Storage', 'Fuel Storage - designated for specific operations.', 3),
(153, 'Medical Lab', 'Medical Lab - designated for specific operations.', 4),
(154, 'Fire Safety Room', 'Fire Safety Room - designated for specific operations.', 5),
(155, 'Server Backup Room', 'Server Backup Room - designated for specific operations.', 1),
(156, 'Central Command', 'Central Command - designated for specific operations.', 2),
(157, 'Satellite Control', 'Satellite Control - designated for specific operations.', 3),
(158, 'AI Development Lab', 'AI Development Lab - designated for specific operations.', 4),
(159, 'Cybersecurity Wing', 'Cybersecurity Wing - designated for specific operations.', 5),
(160, 'Legal Office', 'Legal Office - designated for specific operations.', 1),
(161, 'Archive Room', 'Archive Room - designated for specific operations.', 2),
(162, 'Emergency Response Unit', 'Emergency Response Unit - designated for specific operations.', 3),
(163, 'Drones Testing Zone', 'Drones Testing Zone - designated for specific operations.', 4),
(164, 'Public Relations Office', 'Public Relations Office - designated for specific operations.', 5),
(165, 'Press Conference Room', 'Press Conference Room - designated for specific operations.', 1),
(166, 'Simulation Lab', 'Simulation Lab - designated for specific operations.', 2),
(167, 'Robotics Division', 'Robotics Division - designated for specific operations.', 3),
(168, 'Weapons Testing Facility', 'Weapons Testing Facility - designated for specific operations.', 4),
(169, 'Hazardous Materials Storage', 'Hazardous Materials Storage - designated for specific operations.', 5),
(170, 'Quarantine Zone', 'Quarantine Zone - designated for specific operations.', 1),
(171, 'Biochemical Research Lab', 'Biochemical Research Lab - designated for specific operations.', 2),
(172, 'Nuclear Reactor Room', 'Nuclear Reactor Room - designated for specific operations.', 3),
(173, 'Meteorology Center', 'Meteorology Center - designated for specific operations.', 4),
(174, 'Greenhouse', 'Greenhouse - designated for specific operations.', 5),
(175, 'Animal Testing Lab', 'Animal Testing Lab - designated for specific operations.', 1),
(176, 'Submarine Dock', 'Submarine Dock - designated for specific operations.', 2),
(177, 'Air Traffic Control Tower', 'Air Traffic Control Tower - designated for specific operations.', 3),
(178, 'Aircraft Hangar', 'Aircraft Hangar - designated for specific operations.', 4),
(179, 'Spacecraft Assembly', 'Spacecraft Assembly - designated for specific operations.', 5),
(180, 'Rocket Testing Facility', 'Rocket Testing Facility - designated for specific operations.', 1),
(181, 'Astronaut Training Center', 'Astronaut Training Center - designated for specific operations.', 2),
(182, 'Underwater Research Lab', 'Underwater Research Lab - designated for specific operations.', 3),
(183, 'Seismology Center', 'Seismology Center - designated for specific operations.', 4),
(184, 'Deep Sea Exploration Unit', 'Deep Sea Exploration Unit - designated for specific operations.', 5),
(185, 'Mineral Extraction Plant', 'Mineral Extraction Plant - designated for specific operations.', 1),
(186, 'Ecological Research Zone', 'Ecological Research Zone - designated for specific operations.', 2),
(187, 'Climate Monitoring Station', 'Climate Monitoring Station - designated for specific operations.', 3),
(188, 'Antarctic Research Base', 'Antarctic Research Base - designated for specific operations.', 4),
(189, 'Desert Testing Grounds', 'Desert Testing Grounds - designated for specific operations.', 5),
(190, 'Restricted Area', 'Restricted Area - designated for specific operations.', 1),
(191, 'Warehouse A', 'Warehouse A - designated for specific operations.', 2),
(192, 'Warehouse B', 'Warehouse B - designated for specific operations.', 3),
(193, 'Main Office', 'Main Office - designated for specific operations.', 4),
(194, 'Security Room', 'Security Room - designated for specific operations.', 5),
(195, 'Parking Lot A', 'Parking Lot A - designated for specific operations.', 1),
(196, 'Parking Lot B', 'Parking Lot B - designated for specific operations.', 2),
(197, 'Cafeteria', 'Cafeteria - designated for specific operations.', 3),
(198, 'Laboratory 1', 'Laboratory 1 - designated for specific operations.', 4),
(199, 'Laboratory 2', 'Laboratory 2 - designated for specific operations.', 5),
(200, 'Server Room', 'Server Room - designated for specific operations.', 1),
(201, 'Conference Hall', 'Conference Hall - designated for specific operations.', 2),
(202, 'HR Office', 'HR Office - designated for specific operations.', 3),
(203, 'Reception', 'Reception - designated for specific operations.', 4),
(204, 'Control Center', 'Control Center - designated for specific operations.', 5),
(205, 'Generator Room', 'Generator Room - designated for specific operations.', 1),
(206, 'Data Center', 'Data Center - designated for specific operations.', 2),
(207, 'R&D Unit', 'R&D Unit - designated for specific operations.', 3),
(208, 'Assembly Line A', 'Assembly Line A - designated for specific operations.', 4),
(209, 'Assembly Line B', 'Assembly Line B - designated for specific operations.', 5),
(210, 'Medical Room', 'Medical Room - designated for specific operations.', 1),
(211, 'Break Room', 'Break Room - designated for specific operations.', 2),
(212, 'Loading Dock', 'Loading Dock - designated for specific operations.', 3),
(213, 'Testing Facility', 'Testing Facility - designated for specific operations.', 4),
(214, 'Customer Service', 'Customer Service - designated for specific operations.', 5),
(215, 'Executive Office', 'Executive Office - designated for specific operations.', 1),
(216, 'Training Room', 'Training Room - designated for specific operations.', 2),
(217, 'Lobby', 'Lobby - designated for specific operations.', 3),
(218, 'Locker Room', 'Locker Room - designated for specific operations.', 4),
(219, 'Emergency Exit A', 'Emergency Exit A - designated for specific operations.', 5),
(220, 'Emergency Exit B', 'Emergency Exit B - designated for specific operations.', 1),
(221, 'Storage Room 1', 'Storage Room 1 - designated for specific operations.', 2),
(222, 'Storage Room 2', 'Storage Room 2 - designated for specific operations.', 3),
(223, 'Storage Room 3', 'Storage Room 3 - designated for specific operations.', 4),
(224, 'Security Checkpoint', 'Security Checkpoint - designated for specific operations.', 5),
(225, 'Visitor Lounge', 'Visitor Lounge - designated for specific operations.', 1),
(226, 'Observation Deck', 'Observation Deck - designated for specific operations.', 2),
(227, 'Mechanical Room', 'Mechanical Room - designated for specific operations.', 3),
(228, 'Technical Support', 'Technical Support - designated for specific operations.', 4),
(229, 'Assembly Line C', 'Assembly Line C - designated for specific operations.', 5),
(230, 'Shipping Office', 'Shipping Office - designated for specific operations.', 1),
(231, 'Inspection Room', 'Inspection Room - designated for specific operations.', 2),
(232, 'Library', 'Library - designated for specific operations.', 3),
(233, 'Fire Exit A', 'Fire Exit A - designated for specific operations.', 4),
(234, 'Fire Exit B', 'Fire Exit B - designated for specific operations.', 5),
(235, 'Employee Lounge', 'Employee Lounge - designated for specific operations.', 1),
(236, 'Production Floor', 'Production Floor - designated for specific operations.', 2),
(237, 'Maintenance Room', 'Maintenance Room - designated for specific operations.', 3),
(238, 'VIP Lounge', 'VIP Lounge - designated for specific operations.', 4),
(239, 'Research Wing', 'Research Wing - designated for specific operations.', 5),
(240, 'Data Processing Unit', 'Data Processing Unit - designated for specific operations.', 1),
(241, 'Operations Control', 'Operations Control - designated for specific operations.', 2),
(242, 'Management Office', 'Management Office - designated for specific operations.', 3),
(243, 'Surveillance Room', 'Surveillance Room - designated for specific operations.', 4),
(244, 'Underground Bunker', 'Underground Bunker - designated for specific operations.', 5),
(245, 'Solar Panel Area', 'Solar Panel Area - designated for specific operations.', 1),
(246, 'Cooling Plant', 'Cooling Plant - designated for specific operations.', 2),
(247, 'Fuel Storage', 'Fuel Storage - designated for specific operations.', 3),
(248, 'Medical Lab', 'Medical Lab - designated for specific operations.', 4),
(249, 'Fire Safety Room', 'Fire Safety Room - designated for specific operations.', 5),
(250, 'Server Backup Room', 'Server Backup Room - designated for specific operations.', 1),
(251, 'Central Command', 'Central Command - designated for specific operations.', 2),
(252, 'Satellite Control', 'Satellite Control - designated for specific operations.', 3),
(253, 'AI Development Lab', 'AI Development Lab - designated for specific operations.', 4),
(254, 'Cybersecurity Wing', 'Cybersecurity Wing - designated for specific operations.', 5),
(255, 'Legal Office', 'Legal Office - designated for specific operations.', 1),
(256, 'Archive Room', 'Archive Room - designated for specific operations.', 2),
(257, 'Emergency Response Unit', 'Emergency Response Unit - designated for specific operations.', 3),
(258, 'Drones Testing Zone', 'Drones Testing Zone - designated for specific operations.', 4),
(259, 'Public Relations Office', 'Public Relations Office - designated for specific operations.', 5),
(260, 'Press Conference Room', 'Press Conference Room - designated for specific operations.', 1),
(261, 'Simulation Lab', 'Simulation Lab - designated for specific operations.', 2),
(262, 'Robotics Division', 'Robotics Division - designated for specific operations.', 3),
(263, 'Weapons Testing Facility', 'Weapons Testing Facility - designated for specific operations.', 4),
(264, 'Hazardous Materials Storage', 'Hazardous Materials Storage - designated for specific operations.', 5),
(265, 'Quarantine Zone', 'Quarantine Zone - designated for specific operations.', 1),
(266, 'Biochemical Research Lab', 'Biochemical Research Lab - designated for specific operations.', 2),
(267, 'Nuclear Reactor Room', 'Nuclear Reactor Room - designated for specific operations.', 3),
(268, 'Meteorology Center', 'Meteorology Center - designated for specific operations.', 4),
(269, 'Greenhouse', 'Greenhouse - designated for specific operations.', 5),
(270, 'Animal Testing Lab', 'Animal Testing Lab - designated for specific operations.', 1),
(271, 'Submarine Dock', 'Submarine Dock - designated for specific operations.', 2),
(272, 'Air Traffic Control Tower', 'Air Traffic Control Tower - designated for specific operations.', 3),
(273, 'Aircraft Hangar', 'Aircraft Hangar - designated for specific operations.', 4),
(274, 'Spacecraft Assembly', 'Spacecraft Assembly - designated for specific operations.', 5),
(275, 'Rocket Testing Facility', 'Rocket Testing Facility - designated for specific operations.', 1),
(276, 'Astronaut Training Center', 'Astronaut Training Center - designated for specific operations.', 2),
(277, 'Underwater Research Lab', 'Underwater Research Lab - designated for specific operations.', 3),
(278, 'Seismology Center', 'Seismology Center - designated for specific operations.', 4),
(279, 'Deep Sea Exploration Unit', 'Deep Sea Exploration Unit - designated for specific operations.', 5),
(280, 'Mineral Extraction Plant', 'Mineral Extraction Plant - designated for specific operations.', 1),
(281, 'Ecological Research Zone', 'Ecological Research Zone - designated for specific operations.', 2),
(282, 'Climate Monitoring Station', 'Climate Monitoring Station - designated for specific operations.', 3),
(283, 'Antarctic Research Base', 'Antarctic Research Base - designated for specific operations.', 4),
(284, 'Desert Testing Grounds', 'Desert Testing Grounds - designated for specific operations.', 5),
(285, 'Restricted Area', 'Restricted Area - designated for specific operations.', 1),
(286, 'Warehouse A', 'Warehouse A - designated for specific operations.', 2),
(287, 'Warehouse B', 'Warehouse B - designated for specific operations.', 3),
(288, 'Main Office', 'Main Office - designated for specific operations.', 4),
(289, 'Security Room', 'Security Room - designated for specific operations.', 5),
(290, 'Parking Lot A', 'Parking Lot A - designated for specific operations.', 1),
(291, 'Parking Lot B', 'Parking Lot B - designated for specific operations.', 2),
(292, 'Cafeteria', 'Cafeteria - designated for specific operations.', 3),
(293, 'Laboratory 1', 'Laboratory 1 - designated for specific operations.', 4),
(294, 'Laboratory 2', 'Laboratory 2 - designated for specific operations.', 5),
(295, 'Server Room', 'Server Room - designated for specific operations.', 1),
(296, 'Conference Hall', 'Conference Hall - designated for specific operations.', 2),
(297, 'HR Office', 'HR Office - designated for specific operations.', 3),
(298, 'Reception', 'Reception - designated for specific operations.', 4),
(299, 'Control Center', 'Control Center - designated for specific operations.', 5),
(300, 'Generator Room', 'Generator Room - designated for specific operations.', 1),
(301, 'Data Center', 'Data Center - designated for specific operations.', 2),
(302, 'R&D Unit', 'R&D Unit - designated for specific operations.', 3),
(303, 'Assembly Line A', 'Assembly Line A - designated for specific operations.', 4),
(304, 'Assembly Line B', 'Assembly Line B - designated for specific operations.', 5),
(305, 'Medical Room', 'Medical Room - designated for specific operations.', 1),
(306, 'Break Room', 'Break Room - designated for specific operations.', 2),
(307, 'Loading Dock', 'Loading Dock - designated for specific operations.', 3),
(308, 'Testing Facility', 'Testing Facility - designated for specific operations.', 4),
(309, 'Customer Service', 'Customer Service - designated for specific operations.', 5),
(310, 'Executive Office', 'Executive Office - designated for specific operations.', 1),
(311, 'Training Room', 'Training Room - designated for specific operations.', 2),
(312, 'Lobby', 'Lobby - designated for specific operations.', 3),
(313, 'Locker Room', 'Locker Room - designated for specific operations.', 4),
(314, 'Emergency Exit A', 'Emergency Exit A - designated for specific operations.', 5),
(315, 'Emergency Exit B', 'Emergency Exit B - designated for specific operations.', 1),
(316, 'Storage Room 1', 'Storage Room 1 - designated for specific operations.', 2),
(317, 'Storage Room 2', 'Storage Room 2 - designated for specific operations.', 3),
(318, 'Storage Room 3', 'Storage Room 3 - designated for specific operations.', 4),
(319, 'Security Checkpoint', 'Security Checkpoint - designated for specific operations.', 5),
(320, 'Visitor Lounge', 'Visitor Lounge - designated for specific operations.', 1),
(321, 'Observation Deck', 'Observation Deck - designated for specific operations.', 2),
(322, 'Mechanical Room', 'Mechanical Room - designated for specific operations.', 3),
(323, 'Technical Support', 'Technical Support - designated for specific operations.', 4),
(324, 'Assembly Line C', 'Assembly Line C - designated for specific operations.', 5),
(325, 'Shipping Office', 'Shipping Office - designated for specific operations.', 1),
(326, 'Inspection Room', 'Inspection Room - designated for specific operations.', 2),
(327, 'Library', 'Library - designated for specific operations.', 3),
(328, 'Fire Exit A', 'Fire Exit A - designated for specific operations.', 4),
(329, 'Fire Exit B', 'Fire Exit B - designated for specific operations.', 5),
(330, 'Employee Lounge', 'Employee Lounge - designated for specific operations.', 1),
(331, 'Production Floor', 'Production Floor - designated for specific operations.', 2),
(332, 'Maintenance Room', 'Maintenance Room - designated for specific operations.', 3),
(333, 'VIP Lounge', 'VIP Lounge - designated for specific operations.', 4),
(334, 'Research Wing', 'Research Wing - designated for specific operations.', 5),
(335, 'Data Processing Unit', 'Data Processing Unit - designated for specific operations.', 1),
(336, 'Operations Control', 'Operations Control - designated for specific operations.', 2),
(337, 'Management Office', 'Management Office - designated for specific operations.', 3),
(338, 'Surveillance Room', 'Surveillance Room - designated for specific operations.', 4),
(339, 'Underground Bunker', 'Underground Bunker - designated for specific operations.', 5),
(340, 'Solar Panel Area', 'Solar Panel Area - designated for specific operations.', 1),
(341, 'Cooling Plant', 'Cooling Plant - designated for specific operations.', 2),
(342, 'Fuel Storage', 'Fuel Storage - designated for specific operations.', 3),
(343, 'Medical Lab', 'Medical Lab - designated for specific operations.', 4),
(344, 'Fire Safety Room', 'Fire Safety Room - designated for specific operations.', 5),
(345, 'Server Backup Room', 'Server Backup Room - designated for specific operations.', 1),
(346, 'Central Command', 'Central Command - designated for specific operations.', 2),
(347, 'Satellite Control', 'Satellite Control - designated for specific operations.', 3),
(348, 'AI Development Lab', 'AI Development Lab - designated for specific operations.', 4),
(349, 'Cybersecurity Wing', 'Cybersecurity Wing - designated for specific operations.', 5),
(350, 'Legal Office', 'Legal Office - designated for specific operations.', 1),
(351, 'Archive Room', 'Archive Room - designated for specific operations.', 2),
(352, 'Emergency Response Unit', 'Emergency Response Unit - designated for specific operations.', 3),
(353, 'Drones Testing Zone', 'Drones Testing Zone - designated for specific operations.', 4),
(354, 'Public Relations Office', 'Public Relations Office - designated for specific operations.', 5),
(355, 'Press Conference Room', 'Press Conference Room - designated for specific operations.', 1),
(356, 'Simulation Lab', 'Simulation Lab - designated for specific operations.', 2),
(357, 'Robotics Division', 'Robotics Division - designated for specific operations.', 3),
(358, 'Weapons Testing Facility', 'Weapons Testing Facility - designated for specific operations.', 4),
(359, 'Hazardous Materials Storage', 'Hazardous Materials Storage - designated for specific operations.', 5),
(360, 'Quarantine Zone', 'Quarantine Zone - designated for specific operations.', 1),
(361, 'Biochemical Research Lab', 'Biochemical Research Lab - designated for specific operations.', 2),
(362, 'Nuclear Reactor Room', 'Nuclear Reactor Room - designated for specific operations.', 3),
(363, 'Meteorology Center', 'Meteorology Center - designated for specific operations.', 4),
(364, 'Greenhouse', 'Greenhouse - designated for specific operations.', 5),
(365, 'Animal Testing Lab', 'Animal Testing Lab - designated for specific operations.', 1),
(366, 'Submarine Dock', 'Submarine Dock - designated for specific operations.', 2),
(367, 'Air Traffic Control Tower', 'Air Traffic Control Tower - designated for specific operations.', 3),
(368, 'Aircraft Hangar', 'Aircraft Hangar - designated for specific operations.', 4),
(369, 'Spacecraft Assembly', 'Spacecraft Assembly - designated for specific operations.', 5),
(370, 'Rocket Testing Facility', 'Rocket Testing Facility - designated for specific operations.', 1),
(371, 'Astronaut Training Center', 'Astronaut Training Center - designated for specific operations.', 2),
(372, 'Underwater Research Lab', 'Underwater Research Lab - designated for specific operations.', 3),
(373, 'Seismology Center', 'Seismology Center - designated for specific operations.', 4),
(374, 'Deep Sea Exploration Unit', 'Deep Sea Exploration Unit - designated for specific operations.', 5),
(375, 'Mineral Extraction Plant', 'Mineral Extraction Plant - designated for specific operations.', 1),
(376, 'Ecological Research Zone', 'Ecological Research Zone - designated for specific operations.', 2),
(377, 'Climate Monitoring Station', 'Climate Monitoring Station - designated for specific operations.', 3),
(378, 'Antarctic Research Base', 'Antarctic Research Base - designated for specific operations.', 4),
(379, 'Desert Testing Grounds', 'Desert Testing Grounds - designated for specific operations.', 5),
(380, 'Restricted Area', 'Restricted Area - designated for specific operations.', 1),
(381, 'Warehouse A', 'Warehouse A - designated for specific operations.', 2),
(382, 'Warehouse B', 'Warehouse B - designated for specific operations.', 3),
(383, 'Main Office', 'Main Office - designated for specific operations.', 4),
(384, 'Security Room', 'Security Room - designated for specific operations.', 5),
(385, 'Parking Lot A', 'Parking Lot A - designated for specific operations.', 1),
(386, 'Parking Lot B', 'Parking Lot B - designated for specific operations.', 2),
(387, 'Cafeteria', 'Cafeteria - designated for specific operations.', 3),
(388, 'Laboratory 1', 'Laboratory 1 - designated for specific operations.', 4),
(389, 'Laboratory 2', 'Laboratory 2 - designated for specific operations.', 5),
(390, 'Server Room', 'Server Room - designated for specific operations.', 1),
(391, 'Conference Hall', 'Conference Hall - designated for specific operations.', 2),
(392, 'HR Office', 'HR Office - designated for specific operations.', 3),
(393, 'Reception', 'Reception - designated for specific operations.', 4),
(394, 'Control Center', 'Control Center - designated for specific operations.', 5),
(395, 'Generator Room', 'Generator Room - designated for specific operations.', 1),
(396, 'Data Center', 'Data Center - designated for specific operations.', 2),
(397, 'R&D Unit', 'R&D Unit - designated for specific operations.', 3),
(398, 'Assembly Line A', 'Assembly Line A - designated for specific operations.', 4),
(399, 'Assembly Line B', 'Assembly Line B - designated for specific operations.', 5),
(400, 'Medical Room', 'Medical Room - designated for specific operations.', 1);

--Insert into Incident

INSERT INTO Incident (IncidentID, IncidentType, IncidentDate, IncidentDescription, AreaID) VALUES
(1, 'Vandalism', '2020-01-25', 'Vandalism occurred in the designated area.', 365),
(2, 'Medical Emergency', '2021-11-10', 'Medical Emergency occurred in the designated area.', 209),
(3, 'Vandalism', '2023-06-04', 'Vandalism occurred in the designated area.', 7),
(4, 'Lost Property', '2024-07-26', 'Lost Property occurred in the designated area.', 56),
(5, 'Medical Emergency', '2022-02-27', 'Medical Emergency occurred in the designated area.', 70),
(6, 'Employee Injury', '2022-02-23', 'Employee Injury occurred in the designated area.', 126),
(7, 'Workplace Harassment', '2023-08-07', 'Workplace Harassment occurred in the designated area.', 309),
(8, 'Theft Reported', '2024-03-22', 'Theft Reported occurred in the designated area.', 30),
(9, 'Cyber Attack Detected', '2023-03-02', 'Cyber Attack Detected occurred in the designated area.', 329),
(10, 'System Malfunction', '2022-02-22', 'System Malfunction occurred in the designated area.', 309),
(11, 'Equipment Failure', '2024-02-15', 'Equipment Failure occurred in the designated area.', 293),
(12, 'Hazardous Material Exposure', '2020-05-28', 'Hazardous Material Exposure occurred in the designated area.', 92),
(13, 'Equipment Failure', '2023-10-15', 'Equipment Failure occurred in the designated area.', 119),
(14, 'Gas Leak', '2020-06-19', 'Gas Leak occurred in the designated area.', 186),
(15, 'Equipment Failure', '2023-08-13', 'Equipment Failure occurred in the designated area.', 331),
(16, 'Theft Reported', '2022-04-24', 'Theft Reported occurred in the designated area.', 66),
(17, 'Chemical Spill', '2020-12-11', 'Chemical Spill occurred in the designated area.', 354),
(18, 'System Malfunction', '2021-07-08', 'System Malfunction occurred in the designated area.', 104),
(19, 'Employee Injury', '2023-11-18', 'Employee Injury occurred in the designated area.', 373),
(20, 'Suspicious Activity', '2024-08-16', 'Suspicious Activity occurred in the designated area.', 251),
(21, 'Intruder Alert', '2024-07-08', 'Intruder Alert occurred in the designated area.', 170),
(22, 'Employee Injury', '2022-06-18', 'Employee Injury occurred in the designated area.', 34),
(23, 'Gas Leak', '2020-07-21', 'Gas Leak occurred in the designated area.', 124),
(24, 'Lost Property', '2020-05-05', 'Lost Property occurred in the designated area.', 391),
(25, 'Bomb Threat', '2023-11-20', 'Bomb Threat occurred in the designated area.', 272),
(26, 'Unauthorized Access', '2024-03-22', 'Unauthorized Access occurred in the designated area.', 327),
(27, 'Employee Injury', '2023-04-25', 'Employee Injury occurred in the designated area.', 234),
(28, 'Cyber Attack Detected', '2020-01-30', 'Cyber Attack Detected occurred in the designated area.', 194),
(29, 'Lost Property', '2023-03-20', 'Lost Property occurred in the designated area.', 24),
(30, 'Medical Emergency', '2024-08-26', 'Medical Emergency occurred in the designated area.', 348),
(31, 'Theft Reported', '2022-09-24', 'Theft Reported occurred in the designated area.', 218),
(32, 'Gas Leak', '2023-08-13', 'Gas Leak occurred in the designated area.', 157),
(33, 'Hazardous Material Exposure', '2022-09-04', 'Hazardous Material Exposure occurred in the designated area.', 49),
(34, 'Fire Alarm Triggered', '2023-05-24', 'Fire Alarm Triggered occurred in the designated area.', 252),
(35, 'Bomb Threat', '2020-03-10', 'Bomb Threat occurred in the designated area.', 165),
(36, 'Lost Property', '2023-07-25', 'Lost Property occurred in the designated area.', 356),
(37, 'Theft Reported', '2022-03-29', 'Theft Reported occurred in the designated area.', 273),
(38, 'Hazardous Material Exposure', '2024-07-11', 'Hazardous Material Exposure occurred in the designated area.', 214),
(39, 'System Malfunction', '2020-10-14', 'System Malfunction occurred in the designated area.', 101),
(40, 'Vandalism', '2021-02-25', 'Vandalism occurred in the designated area.', 81),
(41, 'Security Breach', '2022-08-30', 'Security Breach occurred in the designated area.', 119),
(42, 'Cyber Attack Detected', '2023-11-17', 'Cyber Attack Detected occurred in the designated area.', 208),
(43, 'System Malfunction', '2021-01-21', 'System Malfunction occurred in the designated area.', 132),
(44, 'Unauthorized Access', '2024-12-08', 'Unauthorized Access occurred in the designated area.', 235),
(45, 'Power Outage', '2023-07-19', 'Power Outage occurred in the designated area.', 243),
(46, 'Medical Emergency', '2024-10-18', 'Medical Emergency occurred in the designated area.', 351),
(47, 'Vandalism', '2024-11-08', 'Vandalism occurred in the designated area.', 61),
(48, 'Hazardous Material Exposure', '2022-06-26', 'Hazardous Material Exposure occurred in the designated area.', 70),
(49, 'Equipment Failure', '2022-03-15', 'Equipment Failure occurred in the designated area.', 350),
(50, 'Cyber Attack Detected', '2021-07-12', 'Cyber Attack Detected occurred in the designated area.', 250),
(51, 'Workplace Harassment', '2023-11-11', 'Workplace Harassment occurred in the designated area.', 50),
(52, 'Chemical Spill', '2024-10-12', 'Chemical Spill occurred in the designated area.', 250),
(53, 'Cyber Attack Detected', '2023-05-08', 'Cyber Attack Detected occurred in the designated area.', 361),
(54, 'Lost Property', '2022-11-06', 'Lost Property occurred in the designated area.', 142),
(55, 'Vandalism', '2020-12-08', 'Vandalism occurred in the designated area.', 266),
(56, 'Fire Alarm Triggered', '2020-03-01', 'Fire Alarm Triggered occurred in the designated area.', 51),
(57, 'Unauthorized Access', '2021-12-29', 'Unauthorized Access occurred in the designated area.', 210),
(58, 'Employee Injury', '2021-08-14', 'Employee Injury occurred in the designated area.', 357),
(59, 'Unauthorized Access', '2024-07-23', 'Unauthorized Access occurred in the designated area.', 394),
(60, 'Lost Property', '2024-10-02', 'Lost Property occurred in the designated area.', 395),
(61, 'Workplace Harassment', '2024-05-03', 'Workplace Harassment occurred in the designated area.', 46),
(62, 'Fire Alarm Triggered', '2021-10-20', 'Fire Alarm Triggered occurred in the designated area.', 69),
(63, 'Power Outage', '2024-07-23', 'Power Outage occurred in the designated area.', 151),
(64, 'Employee Injury', '2021-11-14', 'Employee Injury occurred in the designated area.', 267),
(65, 'Chemical Spill', '2024-07-13', 'Chemical Spill occurred in the designated area.', 46),
(66, 'Data Breach', '2021-01-14', 'Data Breach occurred in the designated area.', 385),
(67, 'Equipment Failure', '2020-10-28', 'Equipment Failure occurred in the designated area.', 358),
(68, 'Employee Injury', '2021-09-21', 'Employee Injury occurred in the designated area.', 326),
(69, 'Equipment Failure', '2022-07-25', 'Equipment Failure occurred in the designated area.', 235),
(70, 'Vandalism', '2024-04-14', 'Vandalism occurred in the designated area.', 144),
(71, 'Medical Emergency', '2023-06-14', 'Medical Emergency occurred in the designated area.', 345),
(72, 'Unauthorized Access', '2022-05-04', 'Unauthorized Access occurred in the designated area.', 354),
(73, 'Hazardous Material Exposure', '2024-10-24', 'Hazardous Material Exposure occurred in the designated area.', 172),
(74, 'Power Outage', '2024-10-22', 'Power Outage occurred in the designated area.', 370),
(75, 'Employee Injury', '2023-12-16', 'Employee Injury occurred in the designated area.', 190),
(76, 'Vandalism', '2022-09-28', 'Vandalism occurred in the designated area.', 302),
(77, 'Vandalism', '2021-12-01', 'Vandalism occurred in the designated area.', 290),
(78, 'Hazardous Material Exposure', '2024-07-08', 'Hazardous Material Exposure occurred in the designated area.', 295),
(79, 'Cyber Attack Detected', '2024-12-17', 'Cyber Attack Detected occurred in the designated area.', 160),
(80, 'Lost Property', '2022-03-27', 'Lost Property occurred in the designated area.', 294),
(81, 'Data Breach', '2023-03-12', 'Data Breach occurred in the designated area.', 101),
(82, 'Hazardous Material Exposure', '2020-06-17', 'Hazardous Material Exposure occurred in the designated area.', 153),
(83, 'Employee Injury', '2021-04-11', 'Employee Injury occurred in the designated area.', 87),
(84, 'Workplace Harassment', '2021-09-06', 'Workplace Harassment occurred in the designated area.', 163),
(85, 'Gas Leak', '2023-08-22', 'Gas Leak occurred in the designated area.', 245),
(86, 'Security Breach', '2021-11-24', 'Security Breach occurred in the designated area.', 185),
(87, 'Vandalism', '2024-01-30', 'Vandalism occurred in the designated area.', 217),
(88, 'Unauthorized Access', '2021-12-09', 'Unauthorized Access occurred in the designated area.', 336),
(89, 'Gas Leak', '2023-07-29', 'Gas Leak occurred in the designated area.', 4),
(90, 'Vandalism', '2024-10-16', 'Vandalism occurred in the designated area.', 178),
(91, 'Workplace Harassment', '2023-10-09', 'Workplace Harassment occurred in the designated area.', 398),
(92, 'Intruder Alert', '2021-06-02', 'Intruder Alert occurred in the designated area.', 111),
(93, 'Unauthorized Access', '2024-10-18', 'Unauthorized Access occurred in the designated area.', 78),
(94, 'Suspicious Activity', '2021-01-08', 'Suspicious Activity occurred in the designated area.', 134),
(95, 'Power Outage', '2023-04-10', 'Power Outage occurred in the designated area.', 390),
(96, 'Intruder Alert', '2022-06-21', 'Intruder Alert occurred in the designated area.', 248),
(97, 'Suspicious Activity', '2023-08-02', 'Suspicious Activity occurred in the designated area.', 84),
(98, 'Security Breach', '2022-02-21', 'Security Breach occurred in the designated area.', 281),
(99, 'System Malfunction', '2022-09-08', 'System Malfunction occurred in the designated area.', 292),
(100, 'System Malfunction', '2020-06-04', 'System Malfunction occurred in the designated area.', 127),
(101, 'Chemical Spill', '2021-12-09', 'Chemical Spill occurred in the designated area.', 343),
(102, 'System Malfunction', '2020-03-23', 'System Malfunction occurred in the designated area.', 267),
(103, 'Bomb Threat', '2022-12-26', 'Bomb Threat occurred in the designated area.', 238),
(104, 'System Malfunction', '2023-04-30', 'System Malfunction occurred in the designated area.', 192),
(105, 'Theft Reported', '2022-11-30', 'Theft Reported occurred in the designated area.', 281),
(106, 'Data Breach', '2023-07-20', 'Data Breach occurred in the designated area.', 24),
(107, 'Power Outage', '2021-03-08', 'Power Outage occurred in the designated area.', 65),
(108, 'Lost Property', '2020-05-27', 'Lost Property occurred in the designated area.', 40),
(109, 'Medical Emergency', '2024-03-15', 'Medical Emergency occurred in the designated area.', 118),
(110, 'Equipment Failure', '2021-11-01', 'Equipment Failure occurred in the designated area.', 390),
(111, 'Equipment Failure', '2020-05-14', 'Equipment Failure occurred in the designated area.', 245),
(112, 'Medical Emergency', '2023-01-10', 'Medical Emergency occurred in the designated area.', 260),
(113, 'Chemical Spill', '2021-09-28', 'Chemical Spill occurred in the designated area.', 292),
(114, 'System Malfunction', '2023-09-09', 'System Malfunction occurred in the designated area.', 375),
(115, 'Theft Reported', '2021-12-27', 'Theft Reported occurred in the designated area.', 135),
(116, 'Suspicious Activity', '2024-12-19', 'Suspicious Activity occurred in the designated area.', 330),
(117, 'Vandalism', '2024-12-10', 'Vandalism occurred in the designated area.', 68),
(118, 'Employee Injury', '2022-11-24', 'Employee Injury occurred in the designated area.', 341),
(119, 'Vandalism', '2024-03-25', 'Vandalism occurred in the designated area.', 353),
(120, 'Unauthorized Access', '2023-02-22', 'Unauthorized Access occurred in the designated area.', 224),
(121, 'Gas Leak', '2023-04-16', 'Gas Leak occurred in the designated area.', 118),
(122, 'Fire Alarm Triggered', '2024-10-24', 'Fire Alarm Triggered occurred in the designated area.', 341),
(123, 'Lost Property', '2024-06-17', 'Lost Property occurred in the designated area.', 328),
(124, 'Chemical Spill', '2023-09-21', 'Chemical Spill occurred in the designated area.', 385),
(125, 'Gas Leak', '2022-03-19', 'Gas Leak occurred in the designated area.', 297),
(126, 'Vandalism', '2021-08-01', 'Vandalism occurred in the designated area.', 188),
(127, 'Vandalism', '2024-10-26', 'Vandalism occurred in the designated area.', 35),
(128, 'Fire Alarm Triggered', '2024-08-12', 'Fire Alarm Triggered occurred in the designated area.', 285),
(129, 'Bomb Threat', '2021-10-21', 'Bomb Threat occurred in the designated area.', 40),
(130, 'Hazardous Material Exposure', '2024-12-06', 'Hazardous Material Exposure occurred in the designated area.', 245),
(131, 'Suspicious Activity', '2023-04-20', 'Suspicious Activity occurred in the designated area.', 316),
(132, 'System Malfunction', '2022-08-19', 'System Malfunction occurred in the designated area.', 249),
(133, 'Hazardous Material Exposure', '2024-12-06', 'Hazardous Material Exposure occurred in the designated area.', 251),
(134, 'Gas Leak', '2021-10-27', 'Gas Leak occurred in the designated area.', 139),
(135, 'Fire Alarm Triggered', '2020-10-23', 'Fire Alarm Triggered occurred in the designated area.', 278),
(136, 'Lost Property', '2021-01-26', 'Lost Property occurred in the designated area.', 321),
(137, 'Lost Property', '2022-06-17', 'Lost Property occurred in the designated area.', 130),
(138, 'System Malfunction', '2020-07-04', 'System Malfunction occurred in the designated area.', 370),
(139, 'Hazardous Material Exposure', '2022-12-14', 'Hazardous Material Exposure occurred in the designated area.', 32),
(140, 'Medical Emergency', '2024-09-21', 'Medical Emergency occurred in the designated area.', 133),
(141, 'Gas Leak', '2023-07-03', 'Gas Leak occurred in the designated area.', 241),
(142, 'Suspicious Activity', '2022-03-18', 'Suspicious Activity occurred in the designated area.', 277),
(143, 'Bomb Threat', '2021-07-09', 'Bomb Threat occurred in the designated area.', 279),
(144, 'System Malfunction', '2024-07-26', 'System Malfunction occurred in the designated area.', 272),
(145, 'Security Breach', '2021-05-13', 'Security Breach occurred in the designated area.', 242),
(146, 'Workplace Harassment', '2022-05-12', 'Workplace Harassment occurred in the designated area.', 140),
(147, 'Bomb Threat', '2021-12-18', 'Bomb Threat occurred in the designated area.', 42),
(148, 'Security Breach', '2021-08-20', 'Security Breach occurred in the designated area.', 316),
(149, 'Hazardous Material Exposure', '2021-05-18', 'Hazardous Material Exposure occurred in the designated area.', 300),
(150, 'Lost Property', '2021-06-01', 'Lost Property occurred in the designated area.', 346),
(151, 'Suspicious Activity', '2022-05-25', 'Suspicious Activity occurred in the designated area.', 175),
(152, 'Lost Property', '2021-05-01', 'Lost Property occurred in the designated area.', 328),
(153, 'Workplace Harassment', '2023-12-04', 'Workplace Harassment occurred in the designated area.', 293),
(154, 'Chemical Spill', '2024-10-21', 'Chemical Spill occurred in the designated area.', 252),
(155, 'System Malfunction', '2022-09-05', 'System Malfunction occurred in the designated area.', 120),
(156, 'Unauthorized Access', '2022-10-23', 'Unauthorized Access occurred in the designated area.', 312),
(157, 'Chemical Spill', '2023-11-16', 'Chemical Spill occurred in the designated area.', 178),
(158, 'Vandalism', '2024-01-21', 'Vandalism occurred in the designated area.', 40),
(159, 'Data Breach', '2020-02-10', 'Data Breach occurred in the designated area.', 150),
(160, 'Cyber Attack Detected', '2021-08-01', 'Cyber Attack Detected occurred in the designated area.', 274),
(161, 'Lost Property', '2022-06-26', 'Lost Property occurred in the designated area.', 228),
(162, 'Employee Injury', '2022-05-23', 'Employee Injury occurred in the designated area.', 8),
(163, 'Lost Property', '2021-01-31', 'Lost Property occurred in the designated area.', 61),
(164, 'Cyber Attack Detected', '2023-10-25', 'Cyber Attack Detected occurred in the designated area.', 137),
(165, 'Employee Injury', '2023-05-23', 'Employee Injury occurred in the designated area.', 204),
(166, 'Security Breach', '2020-12-15', 'Security Breach occurred in the designated area.', 226),
(167, 'Unauthorized Access', '2021-02-27', 'Unauthorized Access occurred in the designated area.', 43),
(168, 'Theft Reported', '2024-01-18', 'Theft Reported occurred in the designated area.', 252),
(169, 'Workplace Harassment', '2024-01-04', 'Workplace Harassment occurred in the designated area.', 39),
(170, 'Unauthorized Access', '2024-07-04', 'Unauthorized Access occurred in the designated area.', 133),
(171, 'Bomb Threat', '2024-12-04', 'Bomb Threat occurred in the designated area.', 30),
(172, 'System Malfunction', '2021-11-10', 'System Malfunction occurred in the designated area.', 371),
(173, 'Theft Reported', '2022-02-26', 'Theft Reported occurred in the designated area.', 114),
(174, 'Hazardous Material Exposure', '2024-12-12', 'Hazardous Material Exposure occurred in the designated area.', 70),
(175, 'Security Breach', '2021-11-23', 'Security Breach occurred in the designated area.', 68),
(176, 'Intruder Alert', '2022-12-26', 'Intruder Alert occurred in the designated area.', 216),
(177, 'Security Breach', '2021-01-06', 'Security Breach occurred in the designated area.', 367),
(178, 'Security Breach', '2020-04-09', 'Security Breach occurred in the designated area.', 284),
(179, 'Hazardous Material Exposure', '2023-06-02', 'Hazardous Material Exposure occurred in the designated area.', 263),
(180, 'Power Outage', '2021-04-01', 'Power Outage occurred in the designated area.', 50),
(181, 'Employee Injury', '2020-10-02', 'Employee Injury occurred in the designated area.', 117),
(182, 'Medical Emergency', '2023-11-01', 'Medical Emergency occurred in the designated area.', 247),
(183, 'Intruder Alert', '2022-06-24', 'Intruder Alert occurred in the designated area.', 57),
(184, 'Chemical Spill', '2020-03-22', 'Chemical Spill occurred in the designated area.', 386),
(185, 'Suspicious Activity', '2021-10-29', 'Suspicious Activity occurred in the designated area.', 241),
(186, 'Workplace Harassment', '2024-12-21', 'Workplace Harassment occurred in the designated area.', 228),
(187, 'Gas Leak', '2022-10-17', 'Gas Leak occurred in the designated area.', 155),
(188, 'Equipment Failure', '2020-06-07', 'Equipment Failure occurred in the designated area.', 57),
(189, 'Gas Leak', '2023-01-07', 'Gas Leak occurred in the designated area.', 177),
(190, 'Medical Emergency', '2023-05-27', 'Medical Emergency occurred in the designated area.', 213),
(191, 'Fire Alarm Triggered', '2020-09-30', 'Fire Alarm Triggered occurred in the designated area.', 42),
(192, 'Bomb Threat', '2022-01-06', 'Bomb Threat occurred in the designated area.', 323),
(193, 'Chemical Spill', '2022-10-24', 'Chemical Spill occurred in the designated area.', 193),
(194, 'Fire Alarm Triggered', '2024-02-10', 'Fire Alarm Triggered occurred in the designated area.', 248),
(195, 'Equipment Failure', '2021-07-29', 'Equipment Failure occurred in the designated area.', 11),
(196, 'Suspicious Activity', '2022-04-21', 'Suspicious Activity occurred in the designated area.', 137),
(197, 'Theft Reported', '2023-11-02', 'Theft Reported occurred in the designated area.', 96),
(198, 'Intruder Alert', '2020-04-06', 'Intruder Alert occurred in the designated area.', 148),
(199, 'Lost Property', '2021-11-01', 'Lost Property occurred in the designated area.', 338),
(200, 'Workplace Harassment', '2020-05-17', 'Workplace Harassment occurred in the designated area.', 234),
(201, 'Intruder Alert', '2023-01-08', 'Intruder Alert occurred in the designated area.', 309),
(202, 'Employee Injury', '2023-11-30', 'Employee Injury occurred in the designated area.', 301),
(203, 'Medical Emergency', '2020-03-26', 'Medical Emergency occurred in the designated area.', 319),
(204, 'Bomb Threat', '2022-04-13', 'Bomb Threat occurred in the designated area.', 123),
(205, 'Gas Leak', '2022-03-26', 'Gas Leak occurred in the designated area.', 245),
(206, 'Security Breach', '2022-08-06', 'Security Breach occurred in the designated area.', 218),
(207, 'Medical Emergency', '2022-11-18', 'Medical Emergency occurred in the designated area.', 319),
(208, 'Suspicious Activity', '2024-09-19', 'Suspicious Activity occurred in the designated area.', 319),
(209, 'Vandalism', '2022-12-14', 'Vandalism occurred in the designated area.', 311),
(210, 'Fire Alarm Triggered', '2020-02-24', 'Fire Alarm Triggered occurred in the designated area.', 62),
(211, 'Lost Property', '2020-02-19', 'Lost Property occurred in the designated area.', 159),
(212, 'Equipment Failure', '2021-09-15', 'Equipment Failure occurred in the designated area.', 165),
(213, 'Hazardous Material Exposure', '2024-06-19', 'Hazardous Material Exposure occurred in the designated area.', 61),
(214, 'Fire Alarm Triggered', '2020-06-27', 'Fire Alarm Triggered occurred in the designated area.', 248),
(215, 'System Malfunction', '2024-02-14', 'System Malfunction occurred in the designated area.', 276),
(216, 'Gas Leak', '2024-01-22', 'Gas Leak occurred in the designated area.', 111),
(217, 'Cyber Attack Detected', '2020-09-23', 'Cyber Attack Detected occurred in the designated area.', 59),
(218, 'Theft Reported', '2021-12-22', 'Theft Reported occurred in the designated area.', 245),
(219, 'Gas Leak', '2024-06-15', 'Gas Leak occurred in the designated area.', 323),
(220, 'Chemical Spill', '2020-08-13', 'Chemical Spill occurred in the designated area.', 225),
(221, 'Gas Leak', '2021-09-20', 'Gas Leak occurred in the designated area.', 186),
(222, 'Equipment Failure', '2022-05-26', 'Equipment Failure occurred in the designated area.', 96),
(223, 'Chemical Spill', '2024-02-13', 'Chemical Spill occurred in the designated area.', 83),
(224, 'Vandalism', '2020-11-18', 'Vandalism occurred in the designated area.', 384),
(225, 'Equipment Failure', '2024-04-14', 'Equipment Failure occurred in the designated area.', 138),
(226, 'Power Outage', '2021-10-19', 'Power Outage occurred in the designated area.', 378),
(227, 'Lost Property', '2024-01-10', 'Lost Property occurred in the designated area.', 203),
(228, 'Vandalism', '2020-09-12', 'Vandalism occurred in the designated area.', 44),
(229, 'System Malfunction', '2024-01-31', 'System Malfunction occurred in the designated area.', 279),
(230, 'Theft Reported', '2020-05-25', 'Theft Reported occurred in the designated area.', 281),
(231, 'Cyber Attack Detected', '2024-05-23', 'Cyber Attack Detected occurred in the designated area.', 346),
(232, 'Data Breach', '2023-01-31', 'Data Breach occurred in the designated area.', 180),
(233, 'Hazardous Material Exposure', '2020-07-05', 'Hazardous Material Exposure occurred in the designated area.', 372),
(234, 'Medical Emergency', '2020-02-21', 'Medical Emergency occurred in the designated area.', 182),
(235, 'Suspicious Activity', '2023-06-27', 'Suspicious Activity occurred in the designated area.', 76),
(236, 'Bomb Threat', '2024-06-02', 'Bomb Threat occurred in the designated area.', 117),
(237, 'Gas Leak', '2021-10-13', 'Gas Leak occurred in the designated area.', 330),
(238, 'Data Breach', '2020-04-05', 'Data Breach occurred in the designated area.', 211),
(239, 'Security Breach', '2020-03-12', 'Security Breach occurred in the designated area.', 44),
(240, 'System Malfunction', '2020-04-26', 'System Malfunction occurred in the designated area.', 96),
(241, 'Employee Injury', '2021-08-07', 'Employee Injury occurred in the designated area.', 255),
(242, 'Unauthorized Access', '2020-05-28', 'Unauthorized Access occurred in the designated area.', 13),
(243, 'Gas Leak', '2021-08-30', 'Gas Leak occurred in the designated area.', 248),
(244, 'Data Breach', '2022-08-22', 'Data Breach occurred in the designated area.', 340),
(245, 'Equipment Failure', '2022-04-04', 'Equipment Failure occurred in the designated area.', 214),
(246, 'Bomb Threat', '2020-01-19', 'Bomb Threat occurred in the designated area.', 60),
(247, 'Suspicious Activity', '2024-10-11', 'Suspicious Activity occurred in the designated area.', 153),
(248, 'Employee Injury', '2022-01-22', 'Employee Injury occurred in the designated area.', 256),
(249, 'Bomb Threat', '2024-10-27', 'Bomb Threat occurred in the designated area.', 219),
(250, 'Bomb Threat', '2020-07-18', 'Bomb Threat occurred in the designated area.', 35),
(251, 'Medical Emergency', '2023-08-09', 'Medical Emergency occurred in the designated area.', 274),
(252, 'Power Outage', '2024-12-23', 'Power Outage occurred in the designated area.', 291),
(253, 'Employee Injury', '2020-04-28', 'Employee Injury occurred in the designated area.', 151),
(254, 'Security Breach', '2020-03-16', 'Security Breach occurred in the designated area.', 142),
(255, 'Lost Property', '2024-11-09', 'Lost Property occurred in the designated area.', 244),
(256, 'Medical Emergency', '2023-05-24', 'Medical Emergency occurred in the designated area.', 9),
(257, 'Vandalism', '2021-03-20', 'Vandalism occurred in the designated area.', 103),
(258, 'Bomb Threat', '2021-06-18', 'Bomb Threat occurred in the designated area.', 371),
(259, 'Workplace Harassment', '2020-08-22', 'Workplace Harassment occurred in the designated area.', 152),
(260, 'Bomb Threat', '2023-06-12', 'Bomb Threat occurred in the designated area.', 41),
(261, 'Power Outage', '2021-08-30', 'Power Outage occurred in the designated area.', 293),
(262, 'Power Outage', '2020-08-21', 'Power Outage occurred in the designated area.', 274),
(263, 'Unauthorized Access', '2022-05-14', 'Unauthorized Access occurred in the designated area.', 399),
(264, 'Theft Reported', '2020-12-18', 'Theft Reported occurred in the designated area.', 137),
(265, 'Theft Reported', '2024-10-19', 'Theft Reported occurred in the designated area.', 329),
(266, 'System Malfunction', '2020-03-30', 'System Malfunction occurred in the designated area.', 215),
(267, 'Unauthorized Access', '2020-07-14', 'Unauthorized Access occurred in the designated area.', 376),
(268, 'Workplace Harassment', '2024-03-12', 'Workplace Harassment occurred in the designated area.', 295),
(269, 'Medical Emergency', '2024-10-17', 'Medical Emergency occurred in the designated area.', 340),
(270, 'Hazardous Material Exposure', '2024-05-25', 'Hazardous Material Exposure occurred in the designated area.', 129),
(271, 'Fire Alarm Triggered', '2020-10-30', 'Fire Alarm Triggered occurred in the designated area.', 156),
(272, 'Equipment Failure', '2024-12-27', 'Equipment Failure occurred in the designated area.', 369),
(273, 'Employee Injury', '2021-05-30', 'Employee Injury occurred in the designated area.', 53),
(274, 'System Malfunction', '2023-12-03', 'System Malfunction occurred in the designated area.', 239),
(275, 'Suspicious Activity', '2021-01-01', 'Suspicious Activity occurred in the designated area.', 70),
(276, 'Chemical Spill', '2022-04-20', 'Chemical Spill occurred in the designated area.', 264),
(277, 'System Malfunction', '2023-11-22', 'System Malfunction occurred in the designated area.', 19),
(278, 'Bomb Threat', '2024-04-15', 'Bomb Threat occurred in the designated area.', 75),
(279, 'Data Breach', '2024-05-18', 'Data Breach occurred in the designated area.', 206),
(280, 'Vandalism', '2021-05-26', 'Vandalism occurred in the designated area.', 8),
(281, 'Employee Injury', '2023-05-08', 'Employee Injury occurred in the designated area.', 262),
(282, 'Cyber Attack Detected', '2023-06-04', 'Cyber Attack Detected occurred in the designated area.', 198),
(283, 'Medical Emergency', '2021-08-04', 'Medical Emergency occurred in the designated area.', 69),
(284, 'Data Breach', '2020-11-18', 'Data Breach occurred in the designated area.', 94),
(285, 'Unauthorized Access', '2021-08-05', 'Unauthorized Access occurred in the designated area.', 370),
(286, 'Hazardous Material Exposure', '2024-11-30', 'Hazardous Material Exposure occurred in the designated area.', 247),
(287, 'Equipment Failure', '2021-01-31', 'Equipment Failure occurred in the designated area.', 218),
(288, 'Cyber Attack Detected', '2024-02-25', 'Cyber Attack Detected occurred in the designated area.', 316),
(289, 'Theft Reported', '2020-09-24', 'Theft Reported occurred in the designated area.', 221),
(290, 'Power Outage', '2020-05-07', 'Power Outage occurred in the designated area.', 95),
(291, 'Workplace Harassment', '2021-07-28', 'Workplace Harassment occurred in the designated area.', 177),
(292, 'Security Breach', '2023-08-13', 'Security Breach occurred in the designated area.', 68),
(293, 'System Malfunction', '2024-08-02', 'System Malfunction occurred in the designated area.', 101),
(294, 'Hazardous Material Exposure', '2024-12-23', 'Hazardous Material Exposure occurred in the designated area.', 91),
(295, 'Fire Alarm Triggered', '2022-11-03', 'Fire Alarm Triggered occurred in the designated area.', 290),
(296, 'System Malfunction', '2024-04-19', 'System Malfunction occurred in the designated area.', 93),
(297, 'Cyber Attack Detected', '2021-03-02', 'Cyber Attack Detected occurred in the designated area.', 215),
(298, 'Hazardous Material Exposure', '2023-06-06', 'Hazardous Material Exposure occurred in the designated area.', 59),
(299, 'Gas Leak', '2020-01-27', 'Gas Leak occurred in the designated area.', 378),
(300, 'Hazardous Material Exposure', '2021-06-28', 'Hazardous Material Exposure occurred in the designated area.', 58),
(301, 'Bomb Threat', '2020-06-27', 'Bomb Threat occurred in the designated area.', 44),
(302, 'Data Breach', '2024-03-26', 'Data Breach occurred in the designated area.', 169),
(303, 'Cyber Attack Detected', '2023-10-04', 'Cyber Attack Detected occurred in the designated area.', 392),
(304, 'Unauthorized Access', '2022-06-29', 'Unauthorized Access occurred in the designated area.', 137),
(305, 'Data Breach', '2023-11-21', 'Data Breach occurred in the designated area.', 303),
(306, 'Power Outage', '2021-05-28', 'Power Outage occurred in the designated area.', 373),
(307, 'System Malfunction', '2023-07-19', 'System Malfunction occurred in the designated area.', 86),
(308, 'Suspicious Activity', '2021-02-08', 'Suspicious Activity occurred in the designated area.', 90),
(309, 'Lost Property', '2021-08-18', 'Lost Property occurred in the designated area.', 16),
(310, 'Data Breach', '2021-12-31', 'Data Breach occurred in the designated area.', 131),
(311, 'Workplace Harassment', '2020-06-26', 'Workplace Harassment occurred in the designated area.', 149),
(312, 'Lost Property', '2022-12-12', 'Lost Property occurred in the designated area.', 264),
(313, 'Medical Emergency', '2023-02-08', 'Medical Emergency occurred in the designated area.', 288),
(314, 'Theft Reported', '2024-09-30', 'Theft Reported occurred in the designated area.', 73),
(315, 'Workplace Harassment', '2023-01-10', 'Workplace Harassment occurred in the designated area.', 255),
(316, 'Power Outage', '2023-06-15', 'Power Outage occurred in the designated area.', 326),
(317, 'Theft Reported', '2020-05-26', 'Theft Reported occurred in the designated area.', 216),
(318, 'Bomb Threat', '2021-06-30', 'Bomb Threat occurred in the designated area.', 383),
(319, 'Equipment Failure', '2021-09-06', 'Equipment Failure occurred in the designated area.', 286),
(320, 'Chemical Spill', '2024-10-07', 'Chemical Spill occurred in the designated area.', 338),
(321, 'Intruder Alert', '2024-04-26', 'Intruder Alert occurred in the designated area.', 248),
(322, 'Medical Emergency', '2023-12-30', 'Medical Emergency occurred in the designated area.', 54),
(323, 'Cyber Attack Detected', '2020-07-29', 'Cyber Attack Detected occurred in the designated area.', 339),
(324, 'Equipment Failure', '2023-02-07', 'Equipment Failure occurred in the designated area.', 107),
(325, 'Suspicious Activity', '2024-10-21', 'Suspicious Activity occurred in the designated area.', 289),
(326, 'Power Outage', '2021-02-18', 'Power Outage occurred in the designated area.', 81),
(327, 'Cyber Attack Detected', '2024-07-27', 'Cyber Attack Detected occurred in the designated area.', 117),
(328, 'Bomb Threat', '2024-03-17', 'Bomb Threat occurred in the designated area.', 297),
(329, 'Data Breach', '2020-02-13', 'Data Breach occurred in the designated area.', 297),
(330, 'Unauthorized Access', '2024-03-28', 'Unauthorized Access occurred in the designated area.', 375),
(331, 'Workplace Harassment', '2023-07-12', 'Workplace Harassment occurred in the designated area.', 278),
(332, 'Lost Property', '2023-01-02', 'Lost Property occurred in the designated area.', 222),
(333, 'Equipment Failure', '2020-11-25', 'Equipment Failure occurred in the designated area.', 111),
(334, 'Chemical Spill', '2021-11-09', 'Chemical Spill occurred in the designated area.', 25),
(335, 'Medical Emergency', '2024-05-26', 'Medical Emergency occurred in the designated area.', 56),
(336, 'Security Breach', '2020-05-10', 'Security Breach occurred in the designated area.', 235),
(337, 'Workplace Harassment', '2023-10-29', 'Workplace Harassment occurred in the designated area.', 315),
(338, 'Bomb Threat', '2024-10-22', 'Bomb Threat occurred in the designated area.', 103),
(339, 'Fire Alarm Triggered', '2024-07-29', 'Fire Alarm Triggered occurred in the designated area.', 255),
(340, 'Medical Emergency', '2020-06-16', 'Medical Emergency occurred in the designated area.', 138),
(341, 'Cyber Attack Detected', '2023-06-30', 'Cyber Attack Detected occurred in the designated area.', 79),
(342, 'Power Outage', '2023-11-04', 'Power Outage occurred in the designated area.', 159),
(343, 'Gas Leak', '2021-01-09', 'Gas Leak occurred in the designated area.', 178),
(344, 'Cyber Attack Detected', '2021-02-17', 'Cyber Attack Detected occurred in the designated area.', 310),
(345, 'Fire Alarm Triggered', '2020-09-11', 'Fire Alarm Triggered occurred in the designated area.', 185),
(346, 'Workplace Harassment', '2024-02-07', 'Workplace Harassment occurred in the designated area.', 370),
(347, 'Chemical Spill', '2024-11-12', 'Chemical Spill occurred in the designated area.', 110),
(348, 'Suspicious Activity', '2023-11-28', 'Suspicious Activity occurred in the designated area.', 201),
(349, 'Workplace Harassment', '2023-06-17', 'Workplace Harassment occurred in the designated area.', 61),
(350, 'Fire Alarm Triggered', '2021-03-13', 'Fire Alarm Triggered occurred in the designated area.', 6),
(351, 'Fire Alarm Triggered', '2020-01-25', 'Fire Alarm Triggered occurred in the designated area.', 127),
(352, 'Vandalism', '2020-03-07', 'Vandalism occurred in the designated area.', 63),
(353, 'Workplace Harassment', '2022-07-03', 'Workplace Harassment occurred in the designated area.', 85),
(354, 'Theft Reported', '2022-11-25', 'Theft Reported occurred in the designated area.', 264),
(355, 'Employee Injury', '2021-09-27', 'Employee Injury occurred in the designated area.', 365),
(356, 'Data Breach', '2021-09-08', 'Data Breach occurred in the designated area.', 399),
(357, 'System Malfunction', '2024-06-19', 'System Malfunction occurred in the designated area.', 87),
(358, 'Theft Reported', '2020-05-10', 'Theft Reported occurred in the designated area.', 250),
(359, 'Chemical Spill', '2022-12-13', 'Chemical Spill occurred in the designated area.', 275),
(360, 'System Malfunction', '2020-01-11', 'System Malfunction occurred in the designated area.', 30),
(361, 'Employee Injury', '2020-09-10', 'Employee Injury occurred in the designated area.', 309),
(362, 'Data Breach', '2022-01-08', 'Data Breach occurred in the designated area.', 17),
(363, 'Vandalism', '2020-07-18', 'Vandalism occurred in the designated area.', 314),
(364, 'Cyber Attack Detected', '2024-12-03', 'Cyber Attack Detected occurred in the designated area.', 315),
(365, 'Workplace Harassment', '2021-12-12', 'Workplace Harassment occurred in the designated area.', 181),
(366, 'System Malfunction', '2022-10-14', 'System Malfunction occurred in the designated area.', 350),
(367, 'Equipment Failure', '2024-10-23', 'Equipment Failure occurred in the designated area.', 198),
(368, 'Security Breach', '2023-05-22', 'Security Breach occurred in the designated area.', 102),
(369, 'Power Outage', '2023-03-24', 'Power Outage occurred in the designated area.', 315),
(370, 'Security Breach', '2022-12-17', 'Security Breach occurred in the designated area.', 324),
(371, 'Chemical Spill', '2024-12-08', 'Chemical Spill occurred in the designated area.', 15),
(372, 'Bomb Threat', '2023-05-28', 'Bomb Threat occurred in the designated area.', 203),
(373, 'Data Breach', '2024-03-25', 'Data Breach occurred in the designated area.', 105),
(374, 'Unauthorized Access', '2022-07-05', 'Unauthorized Access occurred in the designated area.', 258),
(375, 'Chemical Spill', '2021-11-19', 'Chemical Spill occurred in the designated area.', 383),
(376, 'Workplace Harassment', '2022-03-22', 'Workplace Harassment occurred in the designated area.', 292),
(377, 'Lost Property', '2022-10-22', 'Lost Property occurred in the designated area.', 54),
(378, 'System Malfunction', '2022-04-10', 'System Malfunction occurred in the designated area.', 287),
(379, 'Employee Injury', '2023-05-17', 'Employee Injury occurred in the designated area.', 356),
(380, 'Hazardous Material Exposure', '2020-07-08', 'Hazardous Material Exposure occurred in the designated area.', 100),
(381, 'Data Breach', '2023-10-28', 'Data Breach occurred in the designated area.', 318),
(382, 'Chemical Spill', '2021-03-16', 'Chemical Spill occurred in the designated area.', 66),
(383, 'Fire Alarm Triggered', '2020-09-15', 'Fire Alarm Triggered occurred in the designated area.', 122),
(384, 'Equipment Failure', '2022-11-16', 'Equipment Failure occurred in the designated area.', 234),
(385, 'Power Outage', '2024-09-03', 'Power Outage occurred in the designated area.', 331),
(386, 'Security Breach', '2024-02-26', 'Security Breach occurred in the designated area.', 58),
(387, 'Workplace Harassment', '2024-12-14', 'Workplace Harassment occurred in the designated area.', 280),
(388, 'Theft Reported', '2024-01-19', 'Theft Reported occurred in the designated area.', 163),
(389, 'Data Breach', '2020-06-21', 'Data Breach occurred in the designated area.', 375),
(390, 'Workplace Harassment', '2020-10-31', 'Workplace Harassment occurred in the designated area.', 208),
(391, 'Bomb Threat', '2022-03-18', 'Bomb Threat occurred in the designated area.', 342),
(392, 'Bomb Threat', '2022-12-17', 'Bomb Threat occurred in the designated area.', 155),
(393, 'Fire Alarm Triggered', '2022-09-12', 'Fire Alarm Triggered occurred in the designated area.', 47),
(394, 'Data Breach', '2020-06-25', 'Data Breach occurred in the designated area.', 89),
(395, 'Employee Injury', '2021-01-01', 'Employee Injury occurred in the designated area.', 350),
(396, 'Fire Alarm Triggered', '2020-03-05', 'Fire Alarm Triggered occurred in the designated area.', 153),
(397, 'Vandalism', '2022-02-13', 'Vandalism occurred in the designated area.', 90),
(398, 'Gas Leak', '2020-09-17', 'Gas Leak occurred in the designated area.', 41),
(399, 'Medical Emergency', '2021-12-27', 'Medical Emergency occurred in the designated area.', 206),
(400, 'Hazardous Material Exposure', '2024-05-08', 'Hazardous Material Exposure occurred in the designated area.', 175);